const { expect } = require("chai");
const { ethers } = require("hardhat");
const { createOracleKeyPair, prepareKey, encryptForOracle, createKeyDocument, DecryptionOracle } = require("../scripts/lib/erc7573");

// Both "chains" run on one Hardhat network here; the contracts never call each
// other, so the only link between them is the key released by the oracle.
// scripts/crosschain-demo.js runs the same flow on two separate ledgers.
const eur = (amount) => BigInt(Math.round(amount * 100));
const TRADE_ID = 1;
const UNITS = 10n;
const PRICE = eur(1_000);

describe("Cross-chain DvP (ERC-7573 style)", function () {
  this.timeout(20_000);
  const oracleKeys = createOracleKeyPair();

  async function deploy() {
    const [issuer, seller, buyer, oracleSigner, outsider] = await ethers.getSigners();
    const now = (await ethers.provider.getBlock("latest")).timestamp;

    // Asset chain: bond + locking contract
    const bond = await (await ethers.getContractFactory("TokenizedBond")).deploy(
      "Demo Digital Bond", "DDB", ethers.parseEther("1"), 500, 90 * 86400, now + 400 * 86400
    );
    const locking = await (await ethers.getContractFactory("AssetLockingContract")).deploy(await bond.getAddress());
    for (const address of [seller.address, buyer.address, await locking.getAddress()]) {
      await bond.setWhitelisted(address, true);
    }
    await bond.issue(seller.address, 20);

    // Payment chain: cash token + decryption contract
    const cash = await (await ethers.getContractFactory("TokenisedEuro")).deploy();
    const payment = await (await ethers.getContractFactory("PaymentDecryptionContract")).deploy(
      await cash.getAddress(), oracleSigner.address
    );
    await cash.mint(buyer.address, eur(5_000));

    const oracle = new DecryptionOracle({ privateKey: oracleKeys.privateKey, contracts: [await locking.getAddress()] });
    return { bond, locking, cash, payment, oracle, seller, buyer, oracleSigner, outsider };
  }

  // Each key is generated by the counterparty of the party it benefits.
  async function makeKeys(ctx) {
    const contract = await ctx.locking.getAddress();
    return {
      buyerKey: prepareKey({ oraclePublicKey: oracleKeys.publicKey, contract, id: TRADE_ID, outcome: "success" }), // made by seller
      sellerKey: prepareKey({ oraclePublicKey: oracleKeys.publicKey, contract, id: TRADE_ID, outcome: "failure" }), // made by buyer
    };
  }

  async function lockOnAssetChain(ctx, keys) {
    await ctx.locking.connect(ctx.seller).inceptTransfer(TRADE_ID, UNITS, ctx.buyer.address, keys.sellerKey.hash, keys.sellerKey.encrypted);
    await ctx.bond.connect(ctx.seller).approve(await ctx.locking.getAddress(), UNITS);
    await ctx.locking.connect(ctx.buyer).confirmTransfer(TRADE_ID, UNITS, ctx.seller.address, keys.buyerKey.hash, keys.buyerKey.encrypted);
  }

  async function agreeOnPaymentChain(ctx, keys, amount = PRICE) {
    await ctx.payment.connect(ctx.buyer).inceptTransfer(TRADE_ID, amount, ctx.seller.address, keys.buyerKey.encrypted, keys.sellerKey.encrypted);
    await ctx.payment.connect(ctx.seller).confirmTransfer(TRADE_ID, amount, ctx.buyer.address, keys.buyerKey.encrypted, keys.sellerKey.encrypted);
    await ctx.cash.connect(ctx.buyer).approve(await ctx.payment.getAddress(), amount);
  }

  async function runOracle(ctx, tx) {
    const receipt = await tx.wait();
    const released = await ctx.oracle.handleReceipt(ctx.payment.connect(ctx.oracleSigner), receipt);
    expect(released).to.have.length(1);
    return released[0];
  }

  it("locks the seller's bonds on the asset chain", async function () {
    const ctx = await deploy();
    await lockOnAssetChain(ctx, await makeKeys(ctx));
    expect(await ctx.bond.balanceOf(ctx.seller.address)).to.equal(10n);
    expect(await ctx.bond.balanceOf(await ctx.locking.getAddress())).to.equal(UNITS);
  });

  it("success path: payment releases the buyer key, which delivers the bonds", async function () {
    const ctx = await deploy();
    const keys = await makeKeys(ctx);
    await lockOnAssetChain(ctx, keys);
    await agreeOnPaymentChain(ctx, keys);

    const released = await runOracle(ctx, await ctx.payment.connect(ctx.buyer).transferAndDecrypt(TRADE_ID));
    expect(released.success).to.equal(true);
    expect(await ctx.cash.balanceOf(ctx.seller.address)).to.equal(PRICE);

    await expect(ctx.locking.connect(ctx.buyer).transferWithKey(TRADE_ID, released.key))
      .to.emit(ctx.locking, "TokenClaimed");
    expect(await ctx.bond.balanceOf(ctx.buyer.address)).to.equal(UNITS);
  });

  it("failure path: an unfunded payment releases the seller key, which returns the bonds", async function () {
    const ctx = await deploy();
    const keys = await makeKeys(ctx);
    await lockOnAssetChain(ctx, keys);
    await agreeOnPaymentChain(ctx, keys, eur(9_000)); // buyer holds EUR 5,000

    const tx = await ctx.payment.connect(ctx.buyer).transferAndDecrypt(TRADE_ID);
    await expect(tx).to.emit(ctx.payment, "PaymentFailed").withArgs(TRADE_ID, "Payer has insufficient cash");
    const released = await runOracle(ctx, tx);
    expect(released.success).to.equal(false);

    await expect(ctx.locking.connect(ctx.seller).transferWithKey(TRADE_ID, released.key))
      .to.emit(ctx.locking, "TokenReclaimed");
    expect(await ctx.bond.balanceOf(ctx.seller.address)).to.equal(20n);
    expect(await ctx.cash.balanceOf(ctx.buyer.address)).to.equal(eur(5_000));
  });

  it("the seller can cancel an unpaid trade at any time and get the bonds back (no time-lock)", async function () {
    const ctx = await deploy();
    const keys = await makeKeys(ctx);
    await lockOnAssetChain(ctx, keys);
    await agreeOnPaymentChain(ctx, keys);

    const released = await runOracle(ctx, await ctx.payment.connect(ctx.seller).cancelAndDecrypt(TRADE_ID));
    await ctx.locking.connect(ctx.seller).transferWithKey(TRADE_ID, released.key);
    expect(await ctx.bond.balanceOf(ctx.seller.address)).to.equal(20n);

    await expect(ctx.payment.connect(ctx.buyer).transferAndDecrypt(TRADE_ID))
      .to.be.revertedWithCustomError(ctx.payment, "WrongStatus");
  });

  it("only one key is ever released per trade", async function () {
    const ctx = await deploy();
    const keys = await makeKeys(ctx);
    await lockOnAssetChain(ctx, keys);
    await agreeOnPaymentChain(ctx, keys);
    await runOracle(ctx, await ctx.payment.connect(ctx.buyer).transferAndDecrypt(TRADE_ID));

    await expect(ctx.payment.connect(ctx.seller).cancelAndDecrypt(TRADE_ID))
      .to.be.revertedWithCustomError(ctx.payment, "WrongStatus");
    await expect(ctx.payment.connect(ctx.oracleSigner).releaseKey(TRADE_ID, "0x01"))
      .to.be.revertedWithCustomError(ctx.payment, "KeyAlreadyReleased");
  });

  it("a key works only once on the asset chain", async function () {
    const ctx = await deploy();
    const keys = await makeKeys(ctx);
    await lockOnAssetChain(ctx, keys);
    await agreeOnPaymentChain(ctx, keys);
    const released = await runOracle(ctx, await ctx.payment.connect(ctx.buyer).transferAndDecrypt(TRADE_ID));
    await ctx.locking.transferWithKey(TRADE_ID, released.key);

    await expect(ctx.locking.transferWithKey(TRADE_ID, keys.sellerKey.plaintext))
      .to.be.revertedWithCustomError(ctx.locking, "WrongStatus");
  });

  describe("why nobody can cheat", function () {
    it("the buyer only knows the seller key, which can only hurt the buyer", async function () {
      const ctx = await deploy();
      const keys = await makeKeys(ctx);
      await lockOnAssetChain(ctx, keys);

      // The buyer generated sellerKey, so it knows the plaintext. Using it early
      // simply returns the bonds to the seller.
      await ctx.locking.connect(ctx.buyer).transferWithKey(TRADE_ID, keys.sellerKey.plaintext);
      expect(await ctx.bond.balanceOf(ctx.buyer.address)).to.equal(0n);
      expect(await ctx.bond.balanceOf(ctx.seller.address)).to.equal(20n);
    });

    it("a guessed or forged key is rejected", async function () {
      const ctx = await deploy();
      await lockOnAssetChain(ctx, await makeKeys(ctx));
      const forged = createKeyDocument({ contract: await ctx.locking.getAddress(), id: TRADE_ID, outcome: "success" });
      await expect(ctx.locking.connect(ctx.buyer).transferWithKey(TRADE_ID, forged))
        .to.be.revertedWithCustomError(ctx.locking, "InvalidKey");
    });

    it("the seller refuses a payment whose failure key differs from the one on the asset chain", async function () {
      const ctx = await deploy();
      const keys = await makeKeys(ctx);
      await lockOnAssetChain(ctx, keys);
      const swapped = encryptForOracle(oracleKeys.publicKey, Buffer.from("not the seller key"));
      await ctx.payment.connect(ctx.buyer).inceptTransfer(TRADE_ID, PRICE, ctx.seller.address, keys.buyerKey.encrypted, swapped);

      await expect(ctx.payment.connect(ctx.seller).confirmTransfer(TRADE_ID, PRICE, ctx.buyer.address, keys.buyerKey.encrypted, keys.sellerKey.encrypted))
        .to.be.revertedWithCustomError(ctx.payment, "TermsMismatch");
    });

    it("the oracle refuses to release the failure key as a success key", async function () {
      const ctx = await deploy();
      const keys = await makeKeys(ctx);
      expect(() => ctx.oracle.decrypt({ id: TRADE_ID, success: true, encryptedKey: keys.sellerKey.encrypted }))
        .to.throw("this is the failure key");
      expect(() => ctx.oracle.decrypt({ id: 2, success: false, encryptedKey: keys.sellerKey.encrypted }))
        .to.throw("another transfer");
    });

    it("only the oracle can publish a key", async function () {
      const ctx = await deploy();
      const keys = await makeKeys(ctx);
      await agreeOnPaymentChain(ctx, keys);
      await ctx.payment.connect(ctx.buyer).transferAndDecrypt(TRADE_ID);
      await expect(ctx.payment.connect(ctx.outsider).releaseKey(TRADE_ID, keys.buyerKey.plaintext))
        .to.be.revertedWithCustomError(ctx.payment, "OnlyOracle");
    });

    it("bonds cannot be locked before the buyer confirms matching terms", async function () {
      const ctx = await deploy();
      const keys = await makeKeys(ctx);
      await ctx.locking.connect(ctx.seller).inceptTransfer(TRADE_ID, UNITS, ctx.buyer.address, keys.sellerKey.hash, keys.sellerKey.encrypted);
      await ctx.bond.connect(ctx.seller).approve(await ctx.locking.getAddress(), UNITS);
      await expect(ctx.locking.connect(ctx.buyer).confirmTransfer(TRADE_ID, 5n, ctx.seller.address, keys.buyerKey.hash, keys.buyerKey.encrypted))
        .to.be.revertedWithCustomError(ctx.locking, "TermsMismatch");
    });
  });
});
