// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

interface ILockableSecurity {
    function transferFrom(address from, address to, uint256 units) external returns (bool);
    function transfer(address to, uint256 units) external returns (bool);
}

/**
 * @title AssetLockingContract
 * @notice Asset-chain side of a cross-chain DvP, simplified from ERC-7573
 *         (Fries, Kohl-Landgraf; draft).
 * @dev The bond is locked here against two key hashes:
 *      - buyer key: releases the bond to the buyer (published when payment succeeds)
 *      - seller key: returns the bond to the seller (published when payment fails)
 *      Each key's plaintext is generated by the counterparty and only travels
 *      encrypted to the decryption oracle, so neither side holds the key that
 *      would benefit itself. No time-lock is needed.
 *      Simplifications vs. ERC-7573: uint amounts, bytes32 hashes, no
 *      `transaction` payload, no cancel after locking.
 */
contract AssetLockingContract {
    enum Status { None, Incepted, Locked, Claimed, Reclaimed, Cancelled }

    struct Transfer {
        address seller;
        address buyer;
        uint256 units;
        bytes32 keyHashedSeller;
        bytes32 keyHashedBuyer;
        Status status;
    }

    ILockableSecurity public immutable security;
    mapping(uint256 => Transfer) public transfers;

    event TransferIncepted(uint256 indexed id, uint256 units, address from, address to, bytes32 keyHashedSeller, bytes keyEncryptedSeller);
    event TransferConfirmed(uint256 indexed id, uint256 units, address from, address to, bytes32 keyHashedBuyer, bytes keyEncryptedBuyer);
    event TokenLocked(uint256 indexed id);
    event TransferCancelled(uint256 indexed id);
    event TokenClaimed(uint256 indexed id, bytes key);
    event TokenReclaimed(uint256 indexed id, bytes key);

    error InvalidTerms();
    error IdInUse();
    error NotCounterparty();
    error WrongStatus(Status current);
    error TermsMismatch();
    error InvalidKey();

    constructor(address security_) {
        security = ILockableSecurity(security_);
    }

    /// @notice Seller starts: terms plus the hash of the key that lets the seller reclaim.
    function inceptTransfer(
        uint256 id,
        uint256 units,
        address buyer,
        bytes32 keyHashedSeller,
        bytes calldata keyEncryptedSeller
    ) external {
        if (transfers[id].status != Status.None) revert IdInUse();
        if (units == 0 || buyer == address(0) || buyer == msg.sender || keyHashedSeller == bytes32(0)) {
            revert InvalidTerms();
        }
        transfers[id] = Transfer(msg.sender, buyer, units, keyHashedSeller, bytes32(0), Status.Incepted);
        emit TransferIncepted(id, units, msg.sender, buyer, keyHashedSeller, keyEncryptedSeller);
    }

    /**
     * @notice Buyer confirms the same terms plus the hash of the key that lets the
     *         buyer claim. The seller's bonds move into this contract (locked).
     * @dev The seller must have approved this contract for `units` beforehand.
     */
    function confirmTransfer(
        uint256 id,
        uint256 units,
        address seller,
        bytes32 keyHashedBuyer,
        bytes calldata keyEncryptedBuyer
    ) external {
        Transfer storage t = transfers[id];
        if (t.status != Status.Incepted) revert WrongStatus(t.status);
        if (msg.sender != t.buyer) revert NotCounterparty();
        if (units != t.units || seller != t.seller) revert TermsMismatch();
        if (keyHashedBuyer == bytes32(0) || keyHashedBuyer == t.keyHashedSeller) revert InvalidTerms();

        t.keyHashedBuyer = keyHashedBuyer;
        t.status = Status.Locked;
        security.transferFrom(t.seller, address(this), t.units);

        emit TransferConfirmed(id, units, seller, msg.sender, keyHashedBuyer, keyEncryptedBuyer);
        emit TokenLocked(id);
    }

    /// @notice The seller may withdraw before anything is locked.
    function cancelTransfer(uint256 id) external {
        Transfer storage t = transfers[id];
        if (t.status != Status.Incepted) revert WrongStatus(t.status);
        if (msg.sender != t.seller) revert NotCounterparty();
        t.status = Status.Cancelled;
        emit TransferCancelled(id);
    }

    /**
     * @notice Anyone (buyer, seller or a relayer) submits a released key.
     *         The key decides the direction; the caller does not matter.
     */
    function transferWithKey(uint256 id, bytes calldata key) external {
        Transfer storage t = transfers[id];
        if (t.status != Status.Locked) revert WrongStatus(t.status);

        bytes32 hashed = keccak256(key);
        if (hashed == t.keyHashedBuyer) {
            t.status = Status.Claimed;
            security.transfer(t.buyer, t.units);
            emit TokenClaimed(id, key);
        } else if (hashed == t.keyHashedSeller) {
            t.status = Status.Reclaimed;
            security.transfer(t.seller, t.units);
            emit TokenReclaimed(id, key);
        } else {
            revert InvalidKey();
        }
    }
}
