// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

interface IBondRegister {
    function issuer() external view returns (address);
    function balanceOf(address holder) external view returns (uint256);
    function holderCount() external view returns (uint256);
    function holderAt(uint256 index) external view returns (address);
    function annualCouponRateBps() external view returns (uint256);
    function couponInterval() external view returns (uint256);
    function maturityDate() external view returns (uint256);
    function nextCouponDate() external view returns (uint256);
}

/**
 * @title CouponDischarge
 * @notice Coupon servicing as "payment versus discharge", the asset-chain side.
 * @dev Our reading of Fries, Kohl-Landgraf, Prandtl (2026), "Participant-Operated
 *      Settlement Connectors for Digital Bonds", combined with the March 2026
 *      Smart Bond Contract pilot (DZ BANK / KfW):
 *      - At the record date the bond fixes each holder's coupon claim.
 *      - A settlement attempt freezes an outcome commitment: the hashes of a
 *        success key and a failure key, generated by the stateless oracle.
 *      - The cash moves on another ledger. Its outcome decides which key the
 *        oracle reveals.
 *      - The claim is discharged ONLY when this contract accepts the success
 *        preimage. A failure preimage closes the attempt; the claim stays open.
 *      There is deliberately no function that marks a coupon as paid.
 */
contract CouponDischarge {
    enum AttemptStatus { None, AwaitingKeys, Committed, Succeeded, Failed }

    struct Attempt {
        uint256 period;
        address holder;
        uint256 amount;
        bytes32 hashSuccess;
        bytes32 hashFailure;
        AttemptStatus status;
    }

    uint256 public constant BASIS_POINTS = 10_000;
    uint256 public constant YEAR = 365 days;

    IBondRegister public immutable bond;
    address public immutable decryptionOracle;
    uint256 public immutable couponPerUnit; // in cash token units (EUR cents)
    uint256 public immutable firstCouponDate;
    uint256 public immutable couponInterval;
    uint256 public immutable maturityDate;

    mapping(uint256 => bool) public recorded;
    mapping(uint256 => mapping(address => uint256)) public entitlement;
    mapping(uint256 => mapping(address => bool)) public discharged;
    mapping(uint256 => mapping(address => uint256)) public activeAttempt;

    uint256 public attemptCount;
    mapping(uint256 => Attempt) public attempts;

    event CouponRecorded(uint256 indexed period, uint256 recordDate, uint256 totalAmount);
    event SettlementAttemptOpened(uint256 indexed attemptId, uint256 indexed period, address indexed holder, uint256 amount);
    event OutcomeCommitted(uint256 indexed attemptId, bytes32 hashSuccess, bytes keyEncryptedSuccess, bytes32 hashFailure, bytes keyEncryptedFailure);
    event CouponDischarged(uint256 indexed attemptId, uint256 indexed period, address indexed holder, uint256 amount);
    event SettlementAttemptFailed(uint256 indexed attemptId, uint256 indexed period, address indexed holder);

    error InvalidPeriod();
    error CouponNotDue();
    error AlreadyRecorded();
    error NotRecorded();
    error NoEntitlement();
    error AlreadyDischarged();
    error AttemptInProgress();
    error OnlyOracle();
    error WrongStatus(AttemptStatus current);
    error InvalidPreimage();

    constructor(address bond_, uint256 faceValueInCash, address decryptionOracle_) {
        bond = IBondRegister(bond_);
        decryptionOracle = decryptionOracle_;
        couponInterval = bond.couponInterval();
        maturityDate = bond.maturityDate();
        firstCouponDate = bond.nextCouponDate();
        couponPerUnit = (faceValueInCash * bond.annualCouponRateBps() * couponInterval) / (BASIS_POINTS * YEAR);
    }

    function couponDate(uint256 period) public view returns (uint256) {
        if (period == 0) revert InvalidPeriod();
        uint256 date = firstCouponDate + (period - 1) * couponInterval;
        if (date >= maturityDate) revert InvalidPeriod();
        return date;
    }

    /// @notice Record date: fixes every holder's claim for this period.
    function recordCoupon(uint256 period) external {
        if (block.timestamp < couponDate(period)) revert CouponNotDue();
        if (recorded[period]) revert AlreadyRecorded();
        recorded[period] = true;

        uint256 total;
        uint256 count = bond.holderCount();
        for (uint256 i = 0; i < count; i++) {
            address holder = bond.holderAt(i);
            uint256 amount = bond.balanceOf(holder) * couponPerUnit;
            if (amount > 0) {
                entitlement[period][holder] = amount;
                total += amount;
            }
        }
        emit CouponRecorded(period, block.timestamp, total);
    }

    /// @notice Anyone (typically the issuer's connector) opens one settlement attempt for one claim.
    function openAttempt(uint256 period, address holder) external returns (uint256 attemptId) {
        if (!recorded[period]) revert NotRecorded();
        uint256 amount = entitlement[period][holder];
        if (amount == 0) revert NoEntitlement();
        if (discharged[period][holder]) revert AlreadyDischarged();
        if (activeAttempt[period][holder] != 0) revert AttemptInProgress();

        attemptId = ++attemptCount;
        attempts[attemptId] = Attempt(period, holder, amount, bytes32(0), bytes32(0), AttemptStatus.AwaitingKeys);
        activeAttempt[period][holder] = attemptId;
        emit SettlementAttemptOpened(attemptId, period, holder, amount);
    }

    /**
     * @notice The oracle freezes the outcome commitment. It generated both keys,
     *         so nobody (issuer, investor or connector) knows either preimage.
     *         The encrypted keys are published for the payment ledger.
     */
    function commitOutcomeKeys(
        uint256 attemptId,
        bytes32 hashSuccess,
        bytes calldata keyEncryptedSuccess,
        bytes32 hashFailure,
        bytes calldata keyEncryptedFailure
    ) external {
        if (msg.sender != decryptionOracle) revert OnlyOracle();
        Attempt storage a = attempts[attemptId];
        if (a.status != AttemptStatus.AwaitingKeys) revert WrongStatus(a.status);
        a.hashSuccess = hashSuccess;
        a.hashFailure = hashFailure;
        a.status = AttemptStatus.Committed;
        emit OutcomeCommitted(attemptId, hashSuccess, keyEncryptedSuccess, hashFailure, keyEncryptedFailure);
    }

    /**
     * @notice Anyone forwards a released key. Success discharges the claim;
     *         failure only closes this attempt. Forwarding the same key again is
     *         a harmless no-op, so a connector can safely retry.
     */
    function submitOutcome(uint256 attemptId, bytes calldata preimage) external {
        Attempt storage a = attempts[attemptId];
        bytes32 hashed = keccak256(preimage);

        if (a.status == AttemptStatus.Succeeded && hashed == a.hashSuccess) return;
        if (a.status == AttemptStatus.Failed && hashed == a.hashFailure) return;
        if (a.status != AttemptStatus.Committed) revert WrongStatus(a.status);

        if (hashed == a.hashSuccess) {
            a.status = AttemptStatus.Succeeded;
            discharged[a.period][a.holder] = true;
            activeAttempt[a.period][a.holder] = 0;
            emit CouponDischarged(attemptId, a.period, a.holder, a.amount);
        } else if (hashed == a.hashFailure) {
            a.status = AttemptStatus.Failed;
            activeAttempt[a.period][a.holder] = 0;
            emit SettlementAttemptFailed(attemptId, a.period, a.holder);
        } else {
            revert InvalidPreimage();
        }
    }

    /// @notice True while the holder's claim for this period is not yet discharged.
    function isOutstanding(uint256 period, address holder) external view returns (bool) {
        return entitlement[period][holder] > 0 && !discharged[period][holder];
    }
}
